# Generated by Django 5.0.14 on 2026-07-21 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('github_repo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_prompt', models.TextField()),
                ('target_scale', models.CharField(default='Medium (10k-100k DAU)', max_length=100)),
                ('target_budget', models.CharField(default='Standard ($500-$2000/mo)', max_length=100)),
                ('deployment_target', models.CharField(default='AWS EKS / Containerized', max_length=100)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CLARIFYING', 'Clarifying Questions'), ('PROCESSING', 'Processing Blueprint'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='SUBMITTED', max_length=30)),
                ('clarifying_answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epics', models.JSONField(default=list)),
                ('stories', models.JSONField(default=list)),
                ('sprint_plan', models.JSONField(default=dict)),
                ('non_functional_requirements', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_set', to='projects.idea')),
            ],
        ),
    ]
