# Generated by Django 5.0.14 on 2026-07-21 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(default='v1.0.0', max_length=50)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Production Ready'), ('REJECTED', 'Requires Revision'), ('FAILED', 'Failed')], default='GENERATING', max_length=30)),
                ('is_immutable', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='projects.project')),
                ('requirement_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprints', to='projects.requirementset')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('ARCHITECTURE_DIAGRAM', 'Architecture Diagram'), ('ER_SCHEMA', 'ER Schema & Migration SQL'), ('OPENAPI_SPEC', 'OpenAPI 3.0 Spec'), ('FOLDER_TREE', 'Folder Tree & Coding Standards'), ('COST_ESTIMATE', 'Cloud Cost Estimate'), ('SCALING_SIMULATION', 'Scaling Simulation'), ('DR_PLAN', 'Disaster Recovery Plan'), ('COMPLIANCE_REPORT', 'Compliance & Audit Report'), ('OTHER', 'Other Artifact')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('content_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='blueprints.blueprint')),
            ],
        ),
    ]
